# Generated by Django 2.2.5 on 2019-09-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typeword',
            field=models.CharField(default='普通用户', max_length=100),
        ),
    ]
